// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUWuIA8rX4327rjqC1qWokaMSJ8NQEJVA',
    appId: '1:77660467149:web:bc28d001f3fb232c749e84',
    messagingSenderId: '77660467149',
    projectId: 'redora-1fc3a',
    authDomain: 'redora-1fc3a.firebaseapp.com',
    storageBucket: 'redora-1fc3a.firebasestorage.app',
    measurementId: 'G-C24WM5NNEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxazgpCubyJwLZ35k7BGF_5mxBNGn186A',
    appId: '1:77660467149:android:a6e830e085ce0178749e84',
    messagingSenderId: '77660467149',
    projectId: 'redora-1fc3a',
    storageBucket: 'redora-1fc3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMxOqkocUuQUZjUiXu-PFELemQgCftkE',
    appId: '1:77660467149:ios:a4652fbc4d513d19749e84',
    messagingSenderId: '77660467149',
    projectId: 'redora-1fc3a',
    storageBucket: 'redora-1fc3a.firebasestorage.app',
    iosBundleId: 'com.example.redora',
  );
}
